### PR TITLE
Improve helpscout return

### PR DESCRIPTION
**Pull request by Shelob9**
#94

### CODE REVIEW

**Comment by Shelob9** [comment]
- [ ] How to build docs  npx --yes react-scripts buildUsers\jpoll\Local Sites\test\app\public\wp-content\plugins\vendor>
- [ ] Deal with both build scripts clearing dir first.
- [ ] Load access key form, hidden, with logo/spinner in there.
- [ ] Make sure the zip build script includes it

**Comment by Shelob9** [comment]
@zackkatz This is ready for review.

There are now two builds, and when returning from helpscout or other integrations, a React app is rendered, without loading WordPress, at `admin_init`. That is a very minimal access key login form with everything hidden besides the logo.
- https://github.com/trustedlogin/vendor/pull/97/files#diff-564852bc122f56c6101fc1eebec344a3f8a81682d4eb3aa919513258a28d136eR71-R80

I tested this by setting the query params needed, and also in `ReturnScreen` adding 'redirectData' to the `$data` array, it loaded the simplified view and then redirected. 

If the query params are in the URL, but the access key isn't valid (IE the API call to get redirectData makes a WP_Error), then this minimal app build will not be shown, it goes to the normal access key form. Is this good? Not sure we discussed that or not.
- https://github.com/trustedlogin/vendor/pull/97/files#diff-06a2d78e1c6998582492c819f131bf19233dc5838c39f10a839eb1918954fc62R41
- https://github.com/trustedlogin/vendor/pull/97/files#diff-564852bc122f56c6101fc1eebec344a3f8a81682d4eb3aa919513258a28d136eR145-R149

**Comment by Shelob9** [comment]
I checked latest zip. https://github.com/trustedlogin/vendor/pull/97#issuecomment-1137862993

Zip now has `/build` for the "app build" and "/wpbuild" for the admin screen build

Screenshot 2022-05-25 174353

**Comment by zackkatz** [comment]
> If the query params are in the URL, but the access key isn't valid (IE the API call to get redirectData makes a WP_Error), then this minimal app build will not be shown, it goes to the normal access key form. Is this good? Not sure we discussed that or not.

That sounds good, Josh.

**Comment by Shelob9** [comment]
🌵! it works! 

This is a good catch, re: paths and also a better way to handle the find/replace. https://github.com/trustedlogin/vendor/commit/1018b59afbad22a51211f4677407c0369c370d4a

**Pull request merged**
